[package]
name = "specs_db"
version = "0.1.0"
authors = ["Joe Howarth <josephehowarth@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.15.0"
specs-derive = "0.4.0"
hibitset = "0.6.2"
#serde_derive = "1.0.80"
